#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 12 15:38:47 2021

@author: SamR
"""

import numpy as np 
import matplotlib.pyplot as plt
from pylab import *
from scipy.integrate import quad
from scipy.integrate import trapz
from scipy.integrate import simps


x = np.linspace(0,np.pi,100



def func(x):
    return np.sin(x)

err = []

for N in [10, 20, 50, 100]:
    intEq = trapz
    err.append(2.0-intEq)
    print("nom nom nom", err)



print("**************")
print("quad: ")
print(quad(func, 0, np.pi))

print("**************")
print("trapz: ")
print(trapz(func(x), x, np.pi))


print("**************")
print("simps: ")
print(simps(func(x), x, np.pi))

print("**************")