#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 12 15:00:59 2021

@author: SamR
"""

import numpy as np 
import matplotlib.pyplot as plt
from pylab import *
from scipy.integrate import quad
from scipy.integrate import trapz
from scipy.integrate import simps

x = np.linspace(0,np.pi,100)

x10 = np.linspace(0,np.pi,10)
x100 = np.linspace(0,np.pi,100)
x1000 = np.linspace(0,np.pi,1000)
x10000 = np.linspace(0,np.pi,10000)
x100000 = np.linspace(0,np.pi,100000)


def func(x):
    return np.sin(x)

def func10(x10):
    return np.sin(x10)
def func100(x100):
    return np.sin(x100)
def func1000(x1000):
    return np.sin(x1000)
def func10000(x10000):
    return np.sin(x10000)
def func100000(x100000):
    return np.sin(x100000)



print("**************")
print("quad: ")
print(quad(func, 0, np.pi))

print(quad(func10, 0, np.pi))
print(quad(func100, 0, np.pi))
print(quad(func1000, 0, np.pi))
print(quad(func10000, 0, np.pi))
print(quad(func100000, 0, np.pi))

print("**************")
print("trapz: ")
print(trapz(func(x), x, np.pi))

print(trapz(func10(x10), x10, np.pi))
print(trapz(func100(x100), x100, np.pi))
print(trapz(func1000(x1000), x1000, np.pi))
print(trapz(func10000(x10000), x10000, np.pi))
print(trapz(func100000(x100000), x100000, np.pi))

print("**************")
print("simps: ")
print(simps(func(x), x, np.pi))

print(simps(func10(x10), x10, np.pi))
print(simps(func100(x100), x100, np.pi))
print(simps(func1000(x1000), x1000, np.pi))
print(simps(func10000(x10000), x10000, np.pi))
print(simps(func100000(x100000), x100000, np.pi))
print("**************")

